# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Don't include leading/trailing slahes.", unique=True)),
                ('url', models.URLField()),
                ('permanent', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '➡️',
                'verbose_name_plural': '➡️➡️➡️',
            },
        ),
    ]
