# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_sponsor_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(choices=[('h1', '<h1>'), ('h2', '<h2>'), ('h3', '<h3>'), ('partner', 'Partner')], max_length=20),
        ),
    ]
