# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
