# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('claimed_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'claimed invitation',
                'verbose_name_plural': 'claimed invitations',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 32}), editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_name', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(max_length=10, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='claimedinvitation',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claimed', to='slakslakslak.Invitation'),
        ),
    ]
